-- CREATE TABLE conference (
-- 	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
-- 	name varchar(255) not null,
-- 	theme varchar(255) not null,
-- 	date varchar(50) not null ,
-- 	prtspscount INT not null
-- )

-- auto-generated definition
create table CONFERENCE
(
    CONF_ID     BIGINT auto_increment
        primary key,
    DATE        date,
    NAME        VARCHAR(255),
    PRTSPSCOUNT INTEGER,
    THEME       VARCHAR(255)
);
