-- CREATE TABLE talk (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--     name varchar(255) not null,
--     type varchar(255) not null,
--     desc varchar(255) not null ,
--     person varchar(255) not null
-- );

-- auto-generated definition
create table TALK
(
    TALK_ID BIGINT auto_increment
        primary key,
    DESC    VARCHAR(255),
    NAME    VARCHAR(255),
    PERSON  VARCHAR(255),
    TYPE    VARCHAR(255)
);
