CREATE TABLE talk (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     name varchar(255) not null,
     type varchar(255) not null,
     desc varchar(255) not null ,
     person varchar(255) not null
 );

