CREATE TABLE conference (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	theme varchar(255) not null,
	date varchar(50) not null ,
	prtspscount INT not null,
	talkid BIGINT not null ,
    foreign key (talkid) references talk(id)
)
